# Generated by Django 6.0 on 2026-01-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
