# Generated by Django 6.0 on 2026-02-05 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='adr', on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
    ]
