# Generated by Django 6.0 on 2026-01-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
