# Generated by Django 6.0 on 2026-02-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_dept_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(default='test.png', upload_to='image'),
        ),
    ]
