# Generated by Django 6.0 on 2026-02-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
