# Generated by Django 6.0 on 2026-01-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_product_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
